##############################
- name: Set Linux optional facts
  set_fact:
    al_agent_provision_options: "[]"

- name: Set Linux optional fact for using a registration key
  set_fact:
    al_agent_provision_options: "{{ al_agent_provision_options }} + [ \"--key \" + al_agent_registration_key ]"
  when: al_agent_registration_key is defined and al_agent_registration_key != "your_registration_key_here"

- name: Provision Alert Logic Agent
  # KLUDGE: Could not make the role work unless the registration key is passed to the command.
  # The "set_fact" task above does not seem to work as expected.
  #command: "/etc/init.d/al-agent provision {{ al_agent_provision_options | join(' ') }}"
  command: "/etc/init.d/al-agent provision --key '{{ al_agent_registration_key }}'"
  notify:
    - restart al-agent
  tags: provision_al_agent
  when: not al_agent_for_imaging and not agent_provisioned.stat.exists and al_agent_provision_options != "[]"

- name: Provision Alert Logic Agent - for Imaging
  command: "/etc/init.d/al-agent provision {{ al_agent_provision_options | join(' ') }}"
  tags: provision_al_agent
  when: al_agent_for_imaging and not agent_provisioned.stat.exists and al_agent_provision_options != "[]"
